name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    if: contains(github.event.head_commit.message, '[minor]') || contains(github.event.head_commit.message, '[patch]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - if: contains(github.event.head_commit.message, '[minor]')
        run: npm version minor -m "[skip ci] minor bump to %s"
      - if: contains(github.event.head_commit.message, '[patch]')
        run: npm version patch -m "[skip ci] patch bump to %s"
      - run: git push && git push --tags
      - run: npm pack && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}